// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuWjIGewQaqVvuNoXpWrUxmCz38vstPNM',
    appId: '1:407428003511:web:06e1333091d8ec5015bf32',
    messagingSenderId: '407428003511',
    projectId: 'connect-with-people-app',
    authDomain: 'connect-with-people-app.firebaseapp.com',
    storageBucket: 'connect-with-people-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1q1my-5X5GTg5nag2iK5eYU7uRkGjkxw',
    appId: '1:407428003511:android:ce19f041087bc99515bf32',
    messagingSenderId: '407428003511',
    projectId: 'connect-with-people-app',
    storageBucket: 'connect-with-people-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0mlVIjQHf3v3urDe-c9AQiEUuKYXkb0Q',
    appId: '1:407428003511:ios:9d998065e0d1d08815bf32',
    messagingSenderId: '407428003511',
    projectId: 'connect-with-people-app',
    storageBucket: 'connect-with-people-app.firebasestorage.app',
    androidClientId: '407428003511-v2ntli74bol2sp1qrdj972ta6bdlhr37.apps.googleusercontent.com',
    iosClientId: '407428003511-64a4fu8hgn3en2o342mimc7h2o6lsfq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.connectWithPeopleApp',
  );

}