// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhCXQT2HYGVp_hPrcbZsbAhuHDSSYYS4c',
    appId: '1:647270046972:web:ec6526fdff7ffa983dcb79',
    messagingSenderId: '647270046972',
    projectId: 'connect-app-5dc8c',
    authDomain: 'connect-app-5dc8c.firebaseapp.com',
    storageBucket: 'connect-app-5dc8c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtthksvxOVXMJTjIc2aaJcGZETIY_UqQ4',
    appId: '1:647270046972:android:3a54608ea4c016663dcb79',
    messagingSenderId: '647270046972',
    projectId: 'connect-app-5dc8c',
    storageBucket: 'connect-app-5dc8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_OAL-rZ86clLdTR_B63z9Sf6lUb-hY4k',
    appId: '1:647270046972:ios:d85b6450ffa620983dcb79',
    messagingSenderId: '647270046972',
    projectId: 'connect-app-5dc8c',
    storageBucket: 'connect-app-5dc8c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhCXQT2HYGVp_hPrcbZsbAhuHDSSYYS4c',
    appId: '1:647270046972:web:15c226148a3337563dcb79',
    messagingSenderId: '647270046972',
    projectId: 'connect-app-5dc8c',
    authDomain: 'connect-app-5dc8c.firebaseapp.com',
    storageBucket: 'connect-app-5dc8c.firebasestorage.app',
  );
}
